server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ecommerce_categorydb?createDatabaseIfNotExist=true&useSSL=false
    username: ramesha
    password: Ramesha1!
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
      ddl-auto: update
